import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import SideNavbar from "@/components/ui/SideNavbar";


const inter = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Dashboard Ui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

        className={cn(
          "min-h-screen w-full bg-white text-black flex",
          inter.className,
          { "debug-screens": process.env.NODE_ENV === "development" }
        )}
      >
        {/* {sidebar} */}
        {/* <p className="border">Sidebar</p> */}
        <SideNavbar />
        {/* {mainpage} */}
        
        <div className="p-8 w-full">{children}</div>
        
        
      
      </body>
    </html>
  );
}
